name: CI

on: [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-go@v2
  - run: go build
  - run: ./monitor check play.coldeve.online:9000
